### ISSUE TITLE
Healthcheck launch another command.

### ISSUE THREAD

**Issue by SamMousa** [rancher/giddyup#23]
Currently the healthcheck command is intended to be used in a separate container, would it not make sense to instead have it run in the same container like a passthru command?
I'm thinking something like:
`````
giddyup health --check-command /test.h --on-failure-command /fail.sh -p 1620 -- /myservice.sh
````

This way giddyup launches the healthcheck in the same container as the actual service.

Sidenote, does giddyup reap zombie processes?

**Comment by cloudnautique** [comment]
It is not a PID 1 candidate, as it doesn't manage handle any processes. In the newest version of Giddyup there is `giddyup exec` which is aimed at setting things up and then getting out of the way.

We don't have any plans to make Giddyup a PID 1, so you could do something with s6 or other process manager.  Then start both giddyup and your process.

**Comment by SamMousa** [comment]
Ah okay, then i'll keep using tini for that :)

Thanks for the swift response!

**Comment by SamMousa** [comment]
@cloudnautique Could you explain exec in the docs maybe? :)

**Comment by cloudnautique** [comment]
When its ready :)
